# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoMemory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  # Pods for DoMemory
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'CodableFirebase'
  pod 'WaterfallGrid', '~> 0.4.0'

end
